### ISSUE TITLE
Add CSS Toggle Switch

### ISSUE THREAD

**Issue by kkirsche** [mdo/wtf-forms#47]
Would you be interested in a PR for a CSS Toggle switch.

X-Ref: twbs/bootstrap#15783

Live pens:
First as a Pen:
http://codepen.io/kkirsche/pen/emyvPb

Second as a Pen:
http://codepen.io/kkirsche/pen/VYypVe

**Comment by patrickhlauke** [comment]
And I'll reiterate here: needs to have keyboard focus indication, and a proper label...

**Comment by kkirsche** [comment]
Proper label I understand. I've updated pen 2 to use span instead of label allowing a label to be used properly.
http://codepen.io/kkirsche/pen/VYypVe

When you say keyboard focus indication is this simply the :focus highlighting that occurs around most inputs or are you referring to something else?

**Comment by gijsbotje** [comment]
i have a proposal based on the custom form control
https://codepen.io/gijsbotje/pen/rwKMmy

thoughts?

**Comment by valtido** [comment]
@gijsbotje would recommend size controls, that looks too small on my project have to change it manually each time. #just_a_suggestions

**Comment by mdo** [comment]
No plans to add this to this project, but Bootstrap seems like a great place for it.
