### ISSUE TITLE
Not compatible w/ bootstrap 3+

### ISSUE THREAD

**Issue by newmanw** [mdo/wtf-forms#50]
Was using wtf-forms with boostrap 2 and all was fine.  Recently upgraded to bootstrap 3.3.2 and it seems like some of the css classes are conflicting.

here is a plunk:
http://plnkr.co/edit/d0NiqyziiuFLPuh4vP0h?p=preview

Remove bootstrap css and look just fine

**Comment by mdo** [comment]
Yeah, they're not necessarily meant for each other. I won't be adding any CSS to make them work flawlessly together either. Sorry about that.

**Comment by newmanw** [comment]
No, worries.  Saw a few collisions and started to realize just that.
