### ISSUE TITLE
No Style For select With "multiple"

### ISSUE THREAD

**Issue by anorborg** [mdo/wtf-forms#56]
It doesn't look like select multiple is quite supported:

<img width="297" alt="capture 2015-08-26 at 5 25 01 pm" src="https://cloud.githubusercontent.com/assets/264755/9509709/b91c7ff6-4c17-11e5-92f1-d8e4d7b75bf9.png">

**Comment by anorborg** [comment]
I see the limitation in the docs and understood, but sad :-(

**Comment by mdo** [comment]
Yeah, very little we can do for multiple selects in CSS :\.
