### ISSUE TITLE
Adding bootstrap css causes controls to shrink

### ISSUE THREAD

**Issue by smlombardi** [mdo/wtf-forms#59]
In this Pen: http://codepen.io/smlombardi/pen/LpZOYW?editors=110, if I use CodePen's "add CSS"  feature to add in Bootstrap, I get tiny controls:

![screen shot 2015-09-21 at 12 18 26 pm](https://cloud.githubusercontent.com/assets/835148/9997575/e37ab98c-605a-11e5-8b06-6c83bfe98140.png)

This is using //maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css

**Comment by smlombardi** [comment]
It happens in Plunker as well, so there's a conflict somewhere.

**Comment by smlombardi** [comment]
It seems to be related to the 1rem control-indicator width and height.

Any thoughts on providing a version in pixels instead of rem?  Or a way to make this size correctly in rem?

**Comment by mdo** [comment]
Bootstrap 3 and this project aren't compatible without some work to fix any of the collisions. I have no plans to provide that either, sorry. However, the custom forms are part of v4.
