### ISSUE TITLE
Issues adjusting colors of SVG

### ISSUE THREAD

**Issue by smlombardi** [mdo/wtf-forms#60]
I see how you did the coloring of the SVG in the CSS. I wasn't aware you could do this.

I'm a bit confused, since you did not include the assets (SVG) in the download.  Running the embedded code through base64 decoder gives me this (for checkboxes):
````
<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 17.1.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
     viewBox="0 0 8 8" enable-background="new 0 0 8 8" xml:space="preserve">
<path fill="#FFFFFF" d="M6.4,1L5.7,1.7L2.9,4.5L2.1,3.7L1.4,3L0,4.4l0.7,0.7l1.5,1.5l0.7,0.7l0.7-0.7l3.5-3.5l0.7-0.7L6.4,1L6.4,1z"
    />
</svg>
````
Which, when opened in Sketch 3, is the check mark.

I was trying to reverse the colors, so that the shape (the checkmark or the small circle) was a dark on a white control with a blue border.  Essentially, like this:
![screen shot 2015-09-21 at 12 45 57 pm]

I have not been successful.   I can only change the colors there.

Is it possible?Any suggestions on how to work with the SVG?

(https://cloud.githubusercontent.com/assets/835148/9998374/c0cb776a-605e-11e5-8783-415f6a74e51b.png)

**Comment by mdo** [comment]
I changed them in Illustrator manually, but there are ways to pass the fill color in via CSS I believe. See the suggestions in https://github.com/twbs/bootstrap/pull/17222 as an example.
